#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

PROG="/usr/bin/mihomo"
CONF_PATH="/etc/config/mihomo"

start_service() {
    procd_open_instance
    
    procd_set_param command "$PROG"
    procd_append_param command -d "$CONF_PATH"
    procd_set_param limits core="unlimited"
    procd_set_param limits nofile="1000000 1000000"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn

    procd_close_instance

}
